import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nataSans = localFont({
  src: "./fonts/Nata_Sans/NataSans-VariableFont_wght.ttf",
  variable: "--font-nata-sans",
  weight: "100 900",
});

import iconAlaiza from "./assets/icons/iconAlaiza.svg";

export const metadata: Metadata = {
  title: "Form Onboarding",
  description: "Generated by Zelify",
  icons: {
    icon: iconAlaiza.src,
    shortcut: iconAlaiza.src,
    apple: iconAlaiza.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nataSans.variable} suppressHydrationWarning>
      <body
        className="font-sans antialiased bg-white text-slate-900"
      >
        {children}
      </body>
    </html>
  );
}
