import type { Metadata } from "next";
import { Nata_Sans } from "next/font/google";
import "./globals.css";

const nataSans = Nata_Sans({
  variable: "--font-nata-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Form Onboarding",
  description: "Generated by Zelify",
  icons: {
    icon: "/iconAlaiza.svg",
    shortcut: "/iconAlaiza.svg",
    apple: "/iconAlaiza.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nataSans.variable} suppressHydrationWarning>
      <body
        className="font-sans antialiased"
      >
        {children}
      </body>
    </html>
  );
}
